### ISSUE TITLE
Converted to MC 1.12.2, license request.

### ISSUE THREAD

**Issue by ghost** [qidydl/ComputerCraft-WebServer#1]
I forked and ported this old project to 1.12.2 and tweaked it a bit.  I have another MC mod MCF ("Magic Cracker Factory") that has a small assortment of blocks for ComputerCraft that I wanted to add this block to for convenience.  However your license is GPL-2 and mine is MIT.  May I have your permission to include your network code into MCF under the MIT license?  If so I can credit you however you see fit.

**Comment by qidydl** [comment]
Sure, I don't have any problem with MIT licensing. If there's some traceability back to this project that might be nice, even if only so people can check history. I'll see if I can update the repo to provide dual licensing or just switch it to MIT.
